import {combineReducers} from "redux";
import {
    User,
    registerUser,
    logoutUser,
    resetPasswords,
    verifyPasswords,
    getCategories,
    getCategoryProducts,
    getSingleProduct,
    getProducts,
    getRelatedProducts,
    getWishLists,
    addWishLists,
    addCarts,
    getCarts,
    getCartCounts,
    getRecommendProducts,
    updateCarts,
    removeCarts,
    productSpecifications,
    searchs,
    hotDeals,
    buyNows,
    getBanner,
    getProfiles,
    updateProfiles,
    addUserAddress,
    deleteUserAddress,
    getUserAddress,
    getOrders,
    getOrdersDetails,
    addReviews,
    deleteReviews,
    myReviews,
    getReviews,
    checkouts,
    payNows,
    faqs
    

} from "./Reducer";

export default combineReducers({
    User,
    registerUser,
    logoutUser,
    resetPasswords,
    verifyPasswords, 
    getCategories,
    getCategoryProducts,
    getSingleProduct,
    getProducts,
    getRelatedProducts,
    getWishLists,
    addWishLists,
    addCarts,
    getCarts,
    getCartCounts,
    updateCarts,
    removeCarts,
    getRecommendProducts,
    productSpecifications,
    searchs,
    hotDeals,
    buyNows,
    getBanner,
    getProfiles,
    updateProfiles,
    addUserAddress,
    deleteUserAddress,
    getUserAddress,
    getOrders,
    getOrdersDetails,
    addReviews,
    deleteReviews,
    myReviews,
    getReviews,
    checkouts,
    payNows,
    faqs


});